### Obtener todos los ajustes
GET http://localhost:3000/ajustes

### Obtener ajuste por ID
GET http://localhost:3000/ajustes/2

### Crear ajuste
POST http://localhost:3000/ajustes/create
Content-Type: application/json

{
  "caja": 1,
  "movimiento": "ingreso",
  "monto": 1000.00
}

### Actualizar ajuste
PUT http://localhost:3000/ajustes/update/3
Content-Type: application/json

{
  "caja": 1,
  "movimiento": "egreso",
  "monto": 100.00
}

### Eliminar ajuste
DELETE http://localhost:3000/ajustes/delete/1