### Obtener todos los ajustes
GET http://localhost:3000/ajustes

### Obtener ajuste por ID
GET http://localhost:3000/ajustes/1

### Crear ajuste
POST http://localhost:3000/ajustes/create
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100.00,
  "movimiento": "Negativo",
  "moneda_id": 1
}

### Actualizar ajuste
PUT http://localhost:3000/ajustes/update/3
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100.00,
  "movimiento": "Positivo",
  "moneda_id": 1
}

### Eliminar ajuste
DELETE http://localhost:3000/ajustes/delete/3