### Obtener todos los aportes
GET http://localhost:3000/aportes_socio

### Obtener aporte por ID
GET http://localhost:3000/aportes_socio/1

### Crear aporte
POST http://localhost:3000/aportes_socio/create
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100,
  "moneda_id": 1,
  "aporte": "Aporte"
}

### Actualizar aporte
PUT http://localhost:3000/aportes_socio/update/1
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100,
  "moneda_id": 1,
  "aporte": "Aporte"
}

### Eliminar aporte
DELETE http://localhost:3000/aportes_socio/delete/1