### Obtener todos los clientes
GET http://localhost:3000/cajas

### Obtener caja por ID
GET http://localhost:3000/cajas/2

### Crear caja
POST http://localhost:3000/cajas/create
Content-Type: application/json

{
  "nombre": "Caja 2",
  "tipo": "Activo"
}

### Actualizar caja
PUT http://localhost:3000/cajas/update/1
Content-Type: application/json

{
  "nombre": "Caja 1 Actualizada",
  "tipo": "Activo"
}

### Eliminar caja
DELETE http://localhost:3000/cajas/delete/1