### Obtener todos los cajas
GET http://localhost:3000/cajas

### Obtener caja por ID
GET http://localhost:3000/cajas/2

### Crear caja
POST http://localhost:3000/cajas/create
Content-Type: application/json

{
  "nombre": "GZCaja",
  "tipo": "Pesos"
}

### Actualizar caja
PUT http://localhost:3000/cajas/update/1
Content-Type: application/json

{
  "nombre": "caja Actualizado",
  "tipo": "CA"
}

### Eliminar caja
DELETE http://localhost:3000/cajas/delete/10
