### Obtener todos los cajas
GET http://localhost:3000/cajas

### Obtener caja por ID
GET http://localhost:3000/cajas/1

### Crear caja
POST http://localhost:3000/cajas/create
Content-Type: application/json

{
  "nombre": "ALE_USD",
  "moneda": 1,
  "siglas": "GZ",
  "monto": 1000
}

### Actualizar caja
PUT http://localhost:3000/cajas/update/1
Content-Type: application/json

{
  "nombre": "caja Actualizado",
  "moneda": 1,
  "siglas": "GZ",
  "monto": 1000
}

### Eliminar caja
DELETE http://localhost:3000/cajas/delete/5
