### Obtener todos los clientes
GET http://localhost:3000/clientes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb256YWxvLnppbm5pQGV4YW1wbGUuY29tIiwibm9tYnJlIjoiR29uemFsbyIsImFwZWxsaWRvIjoiWmlubmkiLCJpYXQiOjE3NTgxNTM1MjcsImV4cCI6MTc1ODE1NzEyN30.cqMIBIXXqW7HH3yp0c1_dIyJZIFOyVmVR7_7nJ69Jbc
Content-Type: application/json

### Obtener cliente por ID
GET http://localhost:3000/clientes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwibm9tYnJlIjoicGVwZTIiLCJhcGVsbGlkbyI6ImFzZGFkIiwiaWF0IjoxNzU3OTc1MzkzLCJleHAiOjE3NTc5Nzg5OTN9.PKKv-CWHZw3jx2ADvW1leujYEZD-KwRakcCQNVsoa8A
Content-Type: application/json

### Crear cliente
POST http://localhost:3000/clientes/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnb256YWxvLnppbm5pQGV4YW1wbGUuY29tIiwibm9tYnJlIjoiR29uemFsbyIsImFwZWxsaWRvIjoiWmlubmkiLCJpYXQiOjE3NTgxNTM1MjcsImV4cCI6MTc1ODE1NzEyN30.cqMIBIXXqW7HH3yp0c1_dIyJZIFOyVmVR7_7nJ69Jbc
Content-Type: application/json

{
  "nombre": "pepe10",
  "apellido": "Apellido",
  "telefono": "12345678",
  "email": "pepe4@gmail.com",
  "direccion": "direccion"
}

### Actualizar cliente
PUT http://localhost:3000/clientes/update/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiUGVyZXoiLCJpYXQiOjE3NTc2MzE0NDAsImV4cCI6MTc1NzYzNTA0MH0.2S4_QcJfG7-oAeuZ3YlTg8RP0hdzv4PPLJWLEzQXcuI
Content-Type: application/json

{
  "nombre": "Marina",
  "apellido": "Apellido",
  "telefono": "12345678",
  "email": "pepe2@gmail.com",
  "direccion": "direccion"
}

### Eliminar cliente
DELETE http://localhost:3000/clientes/delete/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiUGVyZXoiLCJpYXQiOjE3NTc1MzAyODYsImV4cCI6MTc1NzUzMzg4Nn0.09Nzw2bmAaLDQxr6Ybb5sa_d1dg6xaLLlULcoX5yGIU
Content-Type: application/json