### Obtener todos los costos variables
GET http://localhost:3000/costos_variables

### Obtener costo variable por ID
GET http://localhost:3000/costos_variables/1

### Crear costo variable
POST http://localhost:3000/costos_variables/create
Content-Type: application/json

{
  "caja": 1,
  //"cliente_id": 1,
  "adjudicacion": "Adjudicacion",
  "monto": 100,
  "moneda": 2,
  "venta": 1
}

### Actualizar costo variable
PUT http://localhost:3000/costos_variables/update/1
Content-Type: application/json

{
  "caja": 1,
  //"cliente_id": 1,
  "adjudicacion": "Adjudicacion",
  "monto": 200,
  "moneda": 1,
  "venta": 1
}

### Eliminar costo variable
DELETE http://localhost:3000/costos_variables/delete/1