### Obtener todos los costos fijos
GET http://localhost:3000/costos_fijos

### Obtener costos fijos por ID
GET http://localhost:3000/costos_fijos/1

### Crear costos fijos
POST http://localhost:3000/costos_fijos/create
Content-Type: application/json

{
  "caja": 1,
  "adjudicacion": "NC",
  "monto": 100,
  "moneda": 1
}

### Actualizar costos fijos
PUT http://localhost:3000/costos_fijos/update/5
Content-Type: application/json

{
  "caja": 2,
  "adjudicacion": "Cliente Actualizado",
  "monto": 200,
  "moneda": 1
}

### Eliminar costos fijos
DELETE http://localhost:3000/costos_fijos/delete/6