### Obtener todos los ajustes
GET http://localhost:3000/ajustes

### Obtener cliente por ID
GET http://localhost:3000/ajustes/1

### Crear cliente
POST http://localhost:3000/ajustes/create
Content-Type: application/json

{
  "nombre": "Nuevo Cliente",
  "siglas": "NC",
  "estado": "Activo"
}

### Actualizar cliente
PUT http://localhost:3000/ajustes/update/1
Content-Type: application/json

{
  "nombre": "Cliente Actualizado",
  "siglas": "CA",
  "estado": "Activo"
}

### Eliminar cliente
DELETE http://localhost:3000/ajustes/delete/1