### Obtener todos los dividendos
GET http://localhost:3000/dividendos_socio

### Obtener dividendo por ID
GET http://localhost:3000/dividendos_socio/1

### Crear dividendo
POST http://localhost:3000/dividendos_socio/create
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100
}

### Actualizar dividendo
PUT http://localhost:3000/dividendos_socio/update/1
Content-Type: application/json

{
  "caja_id": 1,
  "monto": 100
}

### Eliminar dividendo
DELETE http://localhost:3000/dividendos_socio/delete/1