### Obtener todos las monedas
GET http://localhost:3000/monedas

### Obtener moneda por ID
GET http://localhost:3000/monedas/4

### Crear moneda
POST http://localhost:3000/monedas/create
Content-Type: application/json

{
  "nombre": "dolarsitoprueba",
  "codigo_iso": "USD"
}

### Actualizar moneda
PUT http://localhost:3000/monedas/update/8
Content-Type: application/json

{
  "nombre": "Dolar2",
  "codigo_iso": "USD"
}

### Eliminar moneda
DELETE http://localhost:3000/monedas/delete/10