### Obtener todos los pagos
GET http://localhost:3000/pagos

### Obtener pago por ID
GET http://localhost:3000/pagos/1

### Crear pago
POST http://localhost:3000/pagos/create
Content-Type: application/json

{
  "venta": 1,
  "caja": 1,
  "monto": 300.0
}

### Actualizar pago
PUT http://localhost:3000/pagos/update/1
Content-Type: application/json

{
  "venta": 1,
  "caja": 2,
  "monto": 300.0
}

### Eliminar pago
DELETE http://localhost:3000/pagos/delete/1