### Obtener todos las tasas
GET http://localhost:3000/tasas

### Obtener tasa por ID
GET http://localhost:3000/tasas/1

### Crear tasa
POST http://localhost:3000/tasas/create
Content-Type: application/json

{
  //"tasa_actual": 1.0,
  //"tasa_nueva": 2.0
  "moneda_origen": 1 ,
  "moneda_destino": 2,
  "tasa": 2
}

### Actualizar tasa
PUT http://localhost:3000/tasas/update/1
Content-Type: application/json

{
  //"tasa_actual": 1.0,
  //"tasa_nueva": 3.0
  "moneda_origen": 1 ,
  "moneda_destino": 2,
  "tasa": 1
}

### Eliminar tasa
DELETE http://localhost:3000/tasas/delete/1