### Obtener todos las transferencias
GET http://localhost:3000/transferencias

### Obtener transferencia por ID
GET http://localhost:3000/transferencias/1

### Crear transferencia
POST http://localhost:3000/transferencias/create
Content-Type: application/json

{
  "caja_origen": 1,
  "caja_destino": 3,
  "monto": 500
}

### Actualizar transferencia
PUT http://localhost:3000/transferencias/update/1
Content-Type: application/json

{
  "caja_origen": 2,
  "caja_destino": 1,
  "monto": 1000,
  "moneda": 1
}

### Eliminar transferencia
DELETE http://localhost:3000/transferencias/delete/2