### Obtener todos las transferencias
GET http://localhost:3000/transferencias

### Obtener transferencia por ID
GET http://localhost:3000/transferencias/1

### Crear transferencia
POST http://localhost:3000/transferencias/create
Content-Type: application/json

{
  "caja_origen_id": 1,
  "caja_destino_id": 2,
  "monto": 1000,
  "moneda_id": 1
}

### Actualizar transferencia
PUT http://localhost:3000/transferencias/update/1
Content-Type: application/json

{
  "caja_origen_id": 2,
  "caja_destino_id": 1,
  "monto": 1000
}

### Eliminar transferencia
DELETE http://localhost:3000/transferencias/delete/2