### Obtener todos los usuarios
GET http://localhost:3000/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoidXNlciIsImVtYWlsIjoiZ29uemFsb0BleGFtcGxlLmNvbSIsIm5vbWJyZSI6IkdvbnphbG8iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImlhdCI6MTc3NTgzMzE0NX0.rakG7w5xaA85G5_UZ8bklHMWwWKEWJohJF2NACJ8X94


### Obtener un usuario por ID
GET http://localhost:3000/usuarios/4

### Iniciar sesión

POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "email": "alejandro@example.com",
    "contrasenia": "123456"
}

### Crear un nuevo usuario

POST http://localhost:3000/usuarios/sign-up
Content-Type: application/json

{
    "rol": "admin",
    "nombre": "Alejandro",
    "apellido": "Decaroli",
    "contrasenia": "123456",
    "email": "alejandro.decaroli@example.com"
}

### Actualizar un usuario

PUT http://localhost:3000/usuarios/update/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqdWFuLnBlcmV6QGV4YW1wbGUuY29tIiwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiUGVyZXoiLCJpYXQiOjE3NTc2MzE0NDAsImV4cCI6MTc1NzYzNTA0MH0.2S4_QcJfG7-oAeuZ3YlTg8RP0hdzv4PPLJWLEzQXcuI
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Perez",
    "contrasenia": "123456",
    "email": "juan.perez@example.com"
}

### Eliminar un usuario
DELETE http://localhost:3000/usuarios/delete/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoidXNlciIsImVtYWlsIjoiZ29uemFsb0BleGFtcGxlLmNvbSIsIm5vbWJyZSI6IkdvbnphbG8iLCJhcGVsbGlkbyI6IkdhcmNpYSIsImlhdCI6MTc3NTgzMzE0NX0.rakG7w5xaA85G5_UZ8bklHMWwWKEWJohJF2NACJ8X94

