### Obtener todos las ventas
GET http://localhost:3000/ventas

### Obtener venta por ID
GET http://localhost:3000/ventas/1

### Crear venta
POST http://localhost:3000/ventas/create
Content-Type: application/json

{
  "cliente": 1,
  "monto_ars": 1000,
  "costo_mano_obra": 100,
  "costo_materiales_viaticos_fletes": 50,
  "costo_comision": 20,
  "monto_usd": 1000,
  "moneda": 1,
  "estado": true
}

### Actualizar venta
PUT http://localhost:3000/ventas/update/1
Content-Type: application/json

{
  "cliente": 10,
  "monto_ars": 1000,
  "costo_mano_obra": 100,
  "costo_materiales_viaticos_fletes": 50,
  "costo_comision": 20,
  "monto_usd": 1000,
  "moneda": 1,
  "estado": true
}

### Eliminar venta
DELETE http://localhost:3000/ventas/delete/1